
<?php echo $this->doctype(); ?>
<html lang="pt-br">
<head>
    <meta charset="utf-8">

    <?php echo $this->headTitle('Anoreg')->setSeparator(' - ')->setAutoEscape(false); ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/datatables.min.css">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="/assets/css/style.css">

    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>

<body>

<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-center">
        <a class="navbar-brand mx-auto" href="/">Anoreg</a>
    </nav>
</header>

<main role="main">
    <?php echo $this->content; ?>
</main>

<footer class="text-muted">
    <section class="jumbotron text-center">
        <div class="container">
            <p class="float-right">
                <a href="#">Voltar ao Topo</a>
            </p>
        </div>
    </section>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/assets/js/jquery-3.3.1.min.js"></script>
<script src="/assets/js/bootstrap.bundle.js"></script>
<script src="/assets/js/datatables.min.js"></script>
<script src="/assets/js/popper.min.js"></script>
<script src="/assets/js/holder.min.js"></script>
<?= $this->inlineScript() ?>
</body>
</html>

