<?php
echo $this->headTitle('P21 Sistemas');
$this->inlineScript()->appendFile('/assets/js/registry.js', 'text/javascript');
/** @var $form \Application\Form\ImportXmlForm */
$form = $this->form;
?>

<section class="jumbotron text-center">

    <div class="container buttons-top">
        <label class="btn btn-primary btn-file" id="import-file-label" for="file">
            Importar XML <?= $this->formElement($form->get('file')); ?>
        </label>
    </div>
    <div class="container">
        <div id="table-container">
            <table id="data-table" style="width: 100%;"
                   class="table table-striped table-bordered dataTable no-footer cell-border nowrap responsive compact">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Telefone</th>
                        <th>E-mail</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</section>